const types = {
  SPEAKING: 'SPEAKING',
  BLOGPOST: 'BLOGPOST',
  ARTICLE_PUBLICATION: 'ARTICLE_PUBLICATION',
  EVENT_ORGANIZATION: 'EVENT_ORGANIZATION',
  HACKATHON: 'HACKATHON',
  OPEN_SOURCE_PROJECT: 'OPEN_SOURCE_PROJECT',
  VIDEO_PODCAST: 'VIDEO_PODCAST',
  FORUM: 'FORUM',
  OTHER: 'OTHER',
}

module.exports = {
  types,
};