on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: ghstars_sync
      # Use the output from the `hello` step
      - name: Get the output time
        run: | 
          echo "The [time] was ${{ steps.ghstars_sync.outputs.time }}"
          echo "The [status] was ${{ steps.ghstars_sync.outputs.status }}"
          echo "The [yt_total] was ${{ steps.ghstars_sync.outputs.yt_total }}"