on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: ghstars_sync
        env:
          YOUTUBE_CHANNEL_FEED: https://www.youtube.com/feeds/videos.xml?channel_id=UCzR2u5RWXWjUh7CwLSvbitA
          GH_STARS_TOKEN: ${{ secrets.GH_STARS_TOKEN }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: | 
          echo "The [time] was ${{ steps.ghstars_sync.outputs.time }}"
          echo "The [total_new_contributions] was ${{ steps.ghstars_sync.outputs.total_new_contributions }}"
